# Generated by Django 3.2 on 2021-05-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0002_auto_20210503_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='highlighted',
        ),
    ]
